### ISSUE TITLE
libcamera-vid not working on RPi Zero W

### ISSUE THREAD

**Issue by AlexUg** [raspberrypi/libcamera-apps#126]
I'm having problems using libcamera-vid on RPi Zero W.
I'm trying to start the video broadcast (the X server is not in use, all commands are invoked over ssh).
Some times I got error:

<details> 
  <summary>output one (trying to connect vlc client)</summary>

   $ libcamera-vid -v -t 0 --inline --listen -o tcp://0.0.0.0:8585
Options:
    verbose: 1
    info_text:#%frame (%fps fps) exp %exp ag %ag dg %dg
    timeout: 0
    width: 640
    height: 480
    output: tcp://0.0.0.0:8585
    post_process_file: 
    rawfull: 0
    preview: default
    qt-preview: 0
    transform: identity
    roi: all
    metering: centre
    exposure: normal
    ev: 0
    awb: auto
    flush: false
    wrap: 0
    brightness: 0
    contrast: 1
    saturation: 1
    sharpness: 1
    framerate: 30
    denoise: auto
    viewfinder-width: 0
    viewfinder-height: 0
    tuning-file: (libcamera)
    lores-width: 0
    lores-height: 0
    bitrate: 0
    profile: 
    level:  
    intra: 0
    inline: 1
    save-pts: 
    codec: h264
    quality (for MJPEG): 50
    keypress: 0
    signal: 0
    initial: record
    split: 0
    segment: 0
    circular: 0
Waiting for client to connect...
Closing Libcamera application(frames displayed 0, dropped 0)
Camera stopped!
Tearing down requests, buffers and configuration
Camera closed
ERROR: *** accept socket failed ***

</details>

some times:

<details> 
  <summary>output two (if wait several minutes this error gone)</summary>

$ libcamera-vid -v -t 0 --inline --listen -o tcp://0.0.0.0:8585
Options:
    verbose: 1
    info_text:#%frame (%fps fps) exp %exp ag %ag dg %dg
    timeout: 0
    width: 640
    height: 480
    output: tcp://0.0.0.0:8585
    post_process_file: 
    rawfull: 0
    preview: default
    qt-preview: 0
    transform: identity
    roi: all
    metering: centre
    exposure: normal
    ev: 0
    awb: auto
    flush: false
    wrap: 0
    brightness: 0
    contrast: 1
    saturation: 1
    sharpness: 1
    framerate: 30
    denoise: auto
    viewfinder-width: 0
    viewfinder-height: 0
    tuning-file: (libcamera)
    lores-width: 0
    lores-height: 0
    bitrate: 0
    profile: 
    level:  
    intra: 0
    inline: 1
    save-pts: 
    codec: h264
    quality (for MJPEG): 50
    keypress: 0
    signal: 0
    initial: record
    split: 0
    segment: 0
    circular: 0
Closing Libcamera application(frames displayed 0, dropped 0)
Camera stopped!
Tearing down requests, buffers and configuration
Camera closed
ERROR: *** failed to bind listen socket ***

</details>

if run without '-v' argument:

<details> 
  <summary>output three</summary>

$ libcamera-vid -t 0 --inline --listen -o tcp://0.0.0.0:8585
Preview window unavailable
[0:49:11.058666580] [734]  INFO Camera camera_manager.cpp:294 libcamera v0.0.0
ERROR: *** no cameras available ***

</details>

I tried running all commands with 'sudo' but no success.

When I using 'raspivid' with 'vlc' the camera works fine.
For example, with command:
`
raspivid -o - -t 0 -n | cvlc -vvv stream:///dev/stdin --sout '#rtp{sdp=rtsp://:8554/}' :demux=h264
`

<details> 
  <summary>System info</summary>

$ uname -s -r -v -m -p -i -o
Linux 5.10.63+ #1459 Wed Oct 6 16:40:27 BST 2021 armv6l unknown unknown GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

$ sudo vcgencmd version
Sep 30 2021 19:23:18 
Copyright (c) 2012 Broadcom
version 51215b4f6e3966401ecd99652a35cf1c25069113 (clean) (release) (start_x)

$ vcgencmd get_camera
supported=1 detected=1

</details>

**Comment by AlexUg** [comment]
```
# Uncomment some or all of these to enable the optional hardware interfaces
dtparam=i2c_arm=on
#dtparam=i2s=on
dtparam=spi=on

# Uncomment this to enable infrared communication.
#dtoverlay=gpio-ir,gpio_pin=17
#dtoverlay=gpio-ir-tx,gpio_pin=18

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
dtoverlay=vc4-fkms-v3d
start_x=1
gpu_mem=128
enable_uart=1

#enable tft display
dtoverlay=rpi-display
```

**Comment by davidplowman** [comment]
Your /boot/config.txt is certainly missing `dtoverlay=imx219` (or whichever camera you're using). Does your display have a touchscreen? I believe that interferes with communications with the camera so you would need `disable_touchscreen=1`.

In the first instance I'm just trying to find out if the camera is working. Attaching a display to the Pi would reveal this, or you could try logging in with `ssh -X` and running `libcamera-hello --qt-preview` and you should get a little remote camera preview on the laptop. Alternatively type `libcamera-still -o test.jpg` and see if it writes a `test.jpg` file.

**Comment by AlexUg** [comment]
At the moment, it is not clear to me why the '-v' argument, which is responsible for the output of additional information, affects the type of error. With the argument error is:
`
ERROR: *** accept socket failed ***
`
without it:
`
ERROR: *** no cameras available ***
`
And this is repeated all the time.

**Comment by AlexUg** [comment]
> Your /boot/config.txt is certainly missing dtoverlay=imx219

I have added this line to /boot/config.txt and rebooted RPi.
```
$ libcamera-still -o test.jpg
[0:04:43.282791235] [556]  INFO Camera camera_manager.cpp:294 libcamera v0.0.0
ERROR: *** no cameras available ***
```

In dmesg I found:

```
[   33.348943] imx219 10-0010: failed to read chip id 219
[   33.351971] imx219: probe of 10-0010 failed with error -5
[   35.048638] imx219_vddl: disabling
[   35.048669] imx219_vdig: disabling
[   35.048687] imx219_vana: disabling
```

**Comment by davidplowman** [comment]
So it sounds like there might be a problem with the `-v` option which we can look at, but in the mean time the biggest problem is obviously the "no cameras" one. That "failed to read chip id 219" message is obviously indicative of the problem. A few things to check:

- Is this an official Raspberry Pi camera board? Non-Raspberry Pi camera boards with the imx219 do not work.
- Has this sensor ever worked with this or any other Raspberry Pi?
- If you temporarily comment out the `dtoverlay=imx219` line, reboot, and try raspistill, does that work?

Thanks!

**Comment by davidplowman** [comment]
Well, if it has worked at some point then it must be an official module. I'm a bit at a loss as to what to suggest next. I've done a completely fresh install of Raspberry Pi OS 32-bit, followed the build instructions precisely, used your /boot;/config.txt (with the added `dtoverlay=imx219`) and it simply works. Is that an experiment you can try (I'm sorry that it's a bit time-consuming?) Or if you can give me any more information as to what might be different about your image than I might be able to try that next week.

That error you're seeing in dmesg is clearly the Arm being unable to communicate with the camera module, so that's the thing we need to resolve. Does i2cdetect show anything (something like `sudo i2cdetect -y 10`)? I believe the imx219 should show up at address 0x10. `i2cdetect -l` will list all the buses if things are different on a PI Zero, I'm not sure!
