### ISSUE TITLE
libcamera-still -o - sends output to a file named -

### ISSUE THREAD

**Issue by knutegit** [raspberrypi/libcamera-apps#139]
libcamera-still -o - sends the image data to a file name - instead of stdout.

Pi4, 2GB, RP camera, PiOS Bullseye 32bit up to date.

**Comment by davidplowman** [comment]
Never crossed my mind that writing to stdout is a thing for libcamera-still / libcamera-jpeg. I'll put it on the list of little things to tidy up. Thanks for pointing it out!

**Comment by davidplowman** [comment]
This fix has been merged now. You can get it either by building from source, or we'll be updating the apt packages in the coming days.

**Comment by naushir** [comment]
Closing, as this has now been fixed.  If there are still any further issue, feel free to re-open.

**Comment by aiot-maker** [comment]
I wonder if this issue has been fixed indeed. I jut downloaded the latest Raspberry Pi OS Lite (as per imager tool the release date is 2021-1030). I event tried to update/upgrade Raspberry PI OS afterwards (sudo apt update, sudo apt full-upgrade). Camera capture works perfectly except I am unable to redirect the image as a buffer to stdout using libcamera-still -n -o -

**Comment by naushir** [comment]
The updated libraries are not yet available in either the OS image or in apt.  This will be happening imminently.  In the meantime, if you need this functionality, you will have to rebuilt the libcamera-apps and libcamera libraries manually.  Instructions can be found [here](https://www.raspberrypi.com/documentation/accessories/camera.html#building-libcamera-and-libcamera-apps) to do this.

**Comment by aiot-maker** [comment]
Fully understood naushir. Thank you so much for your quick reply. I really appreciated.
