### ISSUE TITLE
How to restore "raspicam" apps?

### ISSUE THREAD

**Issue by SuhaylZhao** [raspberrypi/libcamera-apps#140]
Hi,
You know, before the bullseye system, the camera applications were raspistill,raspivid, but after the bullseye was released, the original camera applications raspistill,raspivid all failed, and picamera, a python library, could not be used. I want to restore the original camera application so that the picamera library can continue to be used. What should I do? Any help would be greatly appreciated!

**Comment by davidplowman** [comment]
Hi, there is a forum post here: https://forums.raspberrypi.com/viewtopic.php?t=323390&sid=65b91e146d233b5282246a4e917fe5f1 or alternatively users can continue to use Buster.

**Comment by SuhaylZhao** [comment]
Hi，Thank you very much!!! I have succeeded!

**Comment by davidplowman** [comment]
Great, thanks for letting us know.
