### ISSUE TITLE
problem in signal mode

### ISSUE THREAD

**Issue by ml50us** [raspberrypi/libcamera-apps#159]
i try to run libcamera-still with -s option but the process run continuously until i send SIGUSR2 signal .
the process don't wait after the first image. 
it works well with -k (keypress) option . 
is it normal ? 

libcamera-still --version
libcamera-apps build: 6145daf-intree 27-11-2021 (07:06:36)
libcamera build: v0.0.0+3156-f4070274

**Comment by davidplowman** [comment]
Thanks for reporting this. I'll check it out as soon as I can.

**Comment by davidplowman** [comment]
Yes, sorry about that. I've just pushed a fix here: https://github.com/raspberrypi/libcamera-apps/pull/160

**Comment by davidplowman** [comment]
This has been merged now so I'll close this issue. We'll get it into our apt repository shortly, if the feature is more urgent then libcamera-apps can be built from source.

**Comment by ml50us** [comment]
Yes it works! Thanks
