### ISSUE TITLE
[REQUEST] Real full-screen mode (no black borders)

### ISSUE THREAD

**Issue by FDelporte** [raspberrypi/libcamera-apps#186]
With the following command, the camera can be started to be fullscreen, which is already great!

```
$ libcamera-hello -t 0 -f
```

But with e.g. the Raspberry Pi High Quality camera, which is 4:3 format, you get a black border left and right of the image on a HD output. Could an additional flag be added to force "real full screen", meaning a portion of the top and bottom is cut-off, to fill the whole screen?

**Comment by 6by9** [comment]
Set the width and height to match the aspect ratio of your screen using --wdith --height

Random cropping under the bonnet is almost always the wrong answer.

**Comment by davidplowman** [comment]
In my case I have a 1920x1200 display. If I ask for a 1920x1200 output image (`libcamera-hello --viewfinder-width 1920 --viewfinder-height 1200`) it chooses a 2028x1080 readout from the sensor (you can see this in the console output, though in our most recent code you can actually choose the camera readout mode too). So I can do this:
```
libcamera-hello --viewfinder-width 1920 --viewfinder-height 1200 -f
```
which will fill the display but give me a slightly messed up aspect ratio. But this:
```
libcamera-hello --roi 0.074,0,0.852,1 --viewfinder-width 1920 --viewfinder-height 1200 -f
```
gives me what I want.

There's currently no direct path of communication back from the display code that knows the display size to the camera setup which would have to set the "sensor crop", so we'd have to figure that one out.

**Comment by FDelporte** [comment]
@6by9 unfortunately the width and height values are not used by `libcamera-hello`
From documentation: _For libcamera-hello these parameters have no effect._

@davidplowman will try out tomorrow, thanks for the tip

**Comment by FDelporte** [comment]
@davidplowman that's indeed the right solution! thanks a lot.

```
libcamera-hello --viewfinder-width 1920 --viewfinder-height 1080 -f
```

I'm trying if I can use this as an 'inexpensive' HDMI camera for maker videos (in combination with an Atem, but I see the result is not 100% smooth. Any idea if this is something that can be further improved by additional settings, camera profile...?

Tested on different boards:
* Pi 4 with 4Gb memory + HQ camera: bit shaky
* Pi Zero W Rev 1.1: very shaky, but expected ;-) 
* Pi Zero 2: shaky comparable to Pi 4, but with some stripes in the image when moving with the camera

Or should I move this question to other issue?

**Comment by naushir** [comment]
@FDelporte, it would be best to create a new issue to discuss this problem.  Possibly include a video of the issue you are seeing, the camera system should not be dropping any frames at those resolutions.

Feel free to close this one down if you are happy that it is solved.
