### ISSUE TITLE
Starting EGL preview window from Raspberry Pi OS Bulleye lite

### ISSUE THREAD

**Issue by diruuu** [raspberrypi/libcamera-apps#233]
Need some help.
I tried to use `libcamera-apps` in Raspberry Pi OS lite, it works on DRM mode. But after I installed X server and a window manager, I can't open the preview window from xterm. It says "Preview window unavailable".

What is the minimal requirements to be able to open the preview window on x server?

**Comment by davidplowman** [comment]
Hi, I'm guessing that Raspberry Pi OS Lite has "libcamera-apps-lite" installed via apt. Can you install "libcamera-apps" instead?

**Comment by diruuu** [comment]
> Hi, I'm guessing that Raspberry Pi OS Lite has "libcamera-apps-lite" installed via apt. Can you install "libcamera-apps" instead?

Thank you! this solved the issue.
