### ISSUE TITLE
Advice required regarding a motion capture app

### ISSUE THREAD

**Issue by dantchapman** [raspberrypi/libcamera-apps#275]
I've written a small extension to the libcamera-vid app inspired by the libcamera-detect app. 
I'm using motion_detect post processing. Essentially when motion is detected I change the output to a constructed filename based on time and date.

The app runs fine for several hrs, writing files every time motion is detected, but after a while, the application segfaults.

On motion detected I carry out the following operations:
```
app.StopCamera();
app.Teardown();
...create a filename based on date and time
//Update the options
options->output = filename;
output = std::unique_ptr<Output>(Output::Create(options));
app.SetEncodeOutputReadyCallback(std::bind(&Output::OutputReady, output.get(), _1, _2, _3, _4));
app.ConfigureVideo(get_colourspace_flags(options->codec));
app.StartEncoder();
app.StartCamera();
```
When motion no longer detected (including a min number of frames) I run similar code, swapping back to the original output setting. Is there anything I'm getting wrong at a fundamental level?
This runs fine for hours faithfully capturing videos when motion is detected.

Any advice on how I debug the issue (I'm a bit of a noob with c++)?

**Comment by dantchapman** [comment]
I think I have spotted my problem - I need to release the output each time I switch output. For some reason I don't see a problem on the pi4, only on the pizero.

**Comment by naushir** [comment]
> I think I have spotted my problem - I need to release the output each time I switch output. For some reason I don't see a problem on the pi4, only on the pizero.

Is there anything more we need to look at for this issue?  If not, feel free to close it down.

**Comment by dantchapman** [comment]
The issue can be closed. One last comment: would it be interesting to include a libcamera-app that utilises motion detect? I would be happy to contribute with your guidance

**Comment by dantchapman** [comment]
Just in case anyone else looks at this closed issue: the libcamera_detect app is using the object_detect TensorFlow capability (which is great by the way). I was looking to use the much simpler motion_detect that simply looks at pixel changes. I indeed used the libcamera_detect for inspiration for my motion detecting app that you will find in my fork of the code (though it is extremely rough around the edges). It's now running in my garden on a pizero 2 W collecting videos of the various creatures (and admittedly waving grass/trees).
