### ISSUE TITLE
Arducam OV7675

### ISSUE THREAD

**Issue by laronll** [raspberrypi/libcamera-apps#289]
Does libcamera support ArduCAM OV7675 camera 0.3 MP?

**Comment by 6by9** [comment]
No as that is a parallel camera, so there is no way to connect it to a Pi. It also generally produces fully processed images, not raw, therefore there is little need for libcamera with it.

It has been designed to connect to the Pico microcontroller, and libcamera does not run on that.

**Comment by laronll** [comment]
Ok this can be closed. Thanks.
