### ISSUE TITLE
libcamera-still always chooses maximum resolution RAW data.

### ISSUE THREAD

**Issue by john-ardu** [raspberrypi/libcamera-apps#292]
**Describe the bug**
When I use libcamera-still to take pictures, even I use the `--width`, `--height` options to specify the image resolution, libcamera-still still chooses the maximum resolution as the original data, it seems that libcamera-still chooses to crop on the maximum resolution Cut to the specified resolution.
In fact, if you don't care about memory issues, it's fine to do this, but when we use a camera with a larger resolution or shoot on a device with a smaller memory, even specifying a small resolution can't avoid the memory allocation problem.

**Bug report**
[bug.txt](https://github.com/raspberrypi/libcamera-apps/files/8570121/bug.txt)

**Additional context**
![image](https://user-images.githubusercontent.com/104488091/165471152-b6f7d495-43bd-4d25-9fa5-ab9269468d7a.png)

**Comment by naushir** [comment]
``--width`` and ``--height`` only specify the output resolution of the final image.  You need to specify the ``--mode`` command line parameter to explicitly select a particular camera mode if you do not want the largest sensor mode.  See [here](https://www.raspberrypi.com/documentation/accessories/camera.html#common-command-line-options) for specific useage.

However, you ought to have enough memory even on a Pi Zero device.  Are you seen any captures running out of memory or is this speculative?

**Comment by davidplowman** [comment]
Just to add that the behaviour - choosing the full resolution raw mode - is deliberate as this copies the behaviour or `raspistill` which we are (mostly) trying to emulate. In fact, the initial versions didn't do this, and users complained that it's not like `raspistill`!

In your particular case, `libcamera-still -o test.jpg --width 2028 --height 1520 --mode 2028:1520` should do what you want.

**Comment by john-ardu** [comment]
Thanks for your quick reply,
I missed this option.

> However, you ought to have enough memory even on a Pi Zero device to use the largest sensor resolution. Are you seen any captures running out of memory or is this speculative?

It is enough for V2 or HQ, but not enough for Arducam 64mp.
