### ISSUE TITLE
Installing libcamera-apps and libcamera0 inside an Ubuntu20.04 container from package

### ISSUE THREAD

**Issue by eranroll** [raspberrypi/libcamera-apps#310]
Hi,

I am running an Ubuntu:20.04 container on a Host OS arm64 Raspberry PI OS debian:Bullseye. Similar to the issue I am referencing below.

Currently, I have compiled the libcamera0 and libcamera-apps from source, in order for it to be available in my container. However, this isn't very sustainable.

Is there any more conventional way of installing these libraries inside as part on and Ubuntu:20.04 docker image. Perhaps, some Debian rules or packages which support this OS?

Regards,

@bugsyb
Seems like am running into same lack of knowledge, though applying all what seems to be required proven to be not enough still.
Host OS arm64 Raspberry PI OS debian:Bullseye 
Container Ubuntu:20.04 
```
docker run -it --rm --name devfull --hostname devfull --network=host --privileged -v /dev/:/dev/ -v /run/udev:/run/udev -v /run/dbus/:/run/dbus 
```
In the container:
```
# udevadm control --reload 
# libcamera-hello --list-cameras -n -v
[11:32:55.075806365] [384]  INFO Camera camera_manager.cpp:293 libcamera v0.0.0+3424-e68e0f1e
[11:32:55.147222672] [385]  WARN RPI raspberrypi.cpp:1202 Mismatch between Unicam and CamHelper for embedded data usage!
[11:32:55.149524163] [385] ERROR RPI raspberrypi.cpp:1230 Unicam driver does not use the MediaController, please update your kernel!
[11:32:55.151257234] [385] ERROR RPI raspberrypi.cpp:1129 Failed to register camera imx219 10-0010: -22
Available cameras
-----------------
0 : USB 2.0 Camera: USB Camera [1920x1080] (/base/scb/pcie@7d500000/pci@1,0/usb@1,0-1.2:1.0-0c45:6366)
    Modes: 'MJPEG' : 320x240 640x480 1280x720 1920x1080 1920x1080 
           'YUYV' : 320x240 640x480 640x480 
Closing Libcamera application(frames displayed 0, dropped 0)
Camera stopped!
Tearing down requests, buffers and configuration
Camera closed
```

End of strace look as:
```
openat(AT_FDCWD, "/usr/lib/aarch64/libdebuginfod.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/libdebuginfod.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/video0", O_RDWR) = 3
**openat(AT_FDCWD, "", O_RDONLY)          = -1 ENOENT (No such file or directory)**
openat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/libcamera", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
openat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/libcamera/ipa_rpi.so", O_RDONLY) = 3
openat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/libcamera/ipa_rpi.so.sign", O_RDONLY) = 4
openat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/libcamera/ipa_vimc.so", O_RDONLY) = 3
openat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/libcamera/ipa_vimc.so.sign", O_RDONLY) = 4
```

Interesting is `openat ""` - could this be the case?
All volumes are mapped and all devices under /dev seem to be accessible.

Would you have any suggestions? The referred solution just runs container in privileged mode - and it loosk like something else might be wrong here?

_Originally posted by @bugsyb in https://github.com/raspberrypi/libcamera-apps/issues/270#issuecomment-1064412785_

**Comment by 6by9** [comment]
```
[11:32:55.149524163] [385] ERROR RPI raspberrypi.cpp:1230 Unicam driver does not use the MediaController, please update your kernel!
```
The Raspberry Pi kernel changed the default to needing Media Controller with https://github.com/raspberrypi/linux/commit/94209d7da46151cdd636c8f29c182d5911792996 in March 2022. Presumably Ubuntu hasn't picked up that change.

You may find that using ```dtoverlay=imx219,media-controller=1``` will enable media controller, but it just depends on how old the kernel is.

libcamera-apps do not support UVC (USB) webcams.
