### ISSUE TITLE
Not enough flushes for --save-pts with low framerate

### ISSUE THREAD

**Issue by ptoews** [raspberrypi/libcamera-apps#316]
When using the `--save-pts` argument and a low framerate, the large buffer for the timestamps file prevents flushing to the timestamps file for a long time. For example, having 1 FPS, with an average of 10 bytes per timestamp, the first flush occurs ~410 seconds after start (the buffer is 4096 bytes in my case). Even worse, if the program is interrupted using Ctrl+C, nothing is flushed at all and the file remains empty.

Is it possible to reduce the buffer size, use line buffering, or add an argument for specifying this buffer size?

**Comment by naushir** [comment]
https://github.com/raspberrypi/libcamera-apps/pull/317 ought to fix this up.  You will need to add the ``--flush`` command line option when running.

Let me know if that works for you.

**Comment by naushir** [comment]
This change has now been merged.
