### ISSUE TITLE
Build error of target images

### ISSUE THREAD

**Issue by tthurow** [raspberrypi/libcamera-apps#323]
**Describe the bug**
Build step of target images failed in image/jpeg.cpp

row 476:40:

```
int32_t exposure_time = metadata.get(libcamera::controls::ExposureTime);
```

cannot convert ‘std::optional<int>’ to ‘int32_t’ {aka ‘int’} in initialization

**Comment by naushir** [comment]
This is because of a recent libcamera API change.  A fix for this is under testing at https://github.com/raspberrypi/libcamera-apps/pull/322.

In the meantime, you can build libcamera from [github/raspberrypi/libcamera/ ](https://github.com/raspberrypi/libcamera).

**Comment by naushir** [comment]
#322 has now been merged.
