### ISSUE TITLE
I need the pcb files and schematics please I have all the parts to make one raspberry Pi 4 and one raspberry Pi 3 b+

### ISSUE THREAD

**Issue by frayray909090** [raspberrypi/libcamera-apps#343]
Please I need the files so I can make my own I don’t have 300 in my pocket to buy them from you so I bought all the parts please

**Comment by naushir** [comment]
Sorry this is not at all relevant to this repo.

**Comment by frayray909090** [comment]
Yea I know I’m not fucking dumb I am just wanting the pcb files to make my own

**Comment by frayray909090** [comment]
@naushir naush@raspberrypi.com nice email :D
