### ISSUE TITLE
Saving metadata with libcamera-vid

### ISSUE THREAD

**Issue by ptoews** [raspberrypi/libcamera-apps#345]
Is it possible to save the metadata (exposure time, gain etc. and ideally the results of the algorithms like lux level, color temperature etc.) for each frame recorded by libcamera-vid, similar to ``--save-pts``? I know that there is already an option `--metadata` for libcamera-still (#307).

**Comment by naushir** [comment]
Unfortunately there is no such option at this time.  When we get a chance, we will look to add it.

**Comment by naushir** [comment]
Not planned yet, but we will put this feature on our backlog.

**Comment by davidplowman** [comment]
Actually William has just a little time before he leaves so we may have a quick look into this!

@will-v-pi FYI

**Comment by will-v-pi** [comment]
#358 should add this option, allowing you to output the metadata to either a json file, or in plain text form like in libcamera-still.

**Comment by ptoews** [comment]
Wow that's great (and quick), thank you so much!

**Comment by naushir** [comment]
This has now been merged.
