### ISSUE TITLE
[HELP WANTED] libcamera-detect object variable

### ISSUE THREAD

**Issue by tmsd2001** [raspberrypi/libcamera-apps#350]
Is it possible to deposit the recognized object in the saved image?
could it be possible in the Filename or exif
or draw the object as in the preview with opencv?
In which file should changes be made?

Is it possible to recompile only the libcamera-detekt?

**Comment by naushir** [comment]
> Is it possible to deposit the recognized object in the saved image? could it be possible in the Filename or exif or draw the object as in the preview with opencv? In which file should changes be made?

You can probably do this fairly easily by modifying [libcamera_detect.cpp](https://github.com/raspberrypi/libcamera-apps/blob/main/apps/libcamera_detect.cpp).  If you have something that seems useful, feel free to open a PR to merge it in!

> 
> Is it possible to recompile only the libcamera-detekt?

Yes, you can simply run ``make libcamera_detect`` to only build the libcamera_detect application.

**Comment by tmsd2001** [comment]
I found the variable I was looking for and added it to libcamara-detect.
Can I also open a pull request if the changes are not perfect yet? So that others can improve on this?

**Comment by naushir** [comment]
> I found the variable I was looking for and added it to libcamara-detect.
> Can I also open a pull request if the changes are not perfect yet? So that others can improve on this?

Yes, we will be happy to review your changes!

**Comment by naushir** [comment]
With https://github.com/raspberrypi/libcamera-apps/pull/362 now merged, presumably this can be now closed?
