### ISSUE TITLE
FrameDurations is no longer available

### ISSUE THREAD

**Issue by andrewcsmith** [raspberrypi/libcamera-apps#36]
I'm following the [tutorial here](https://www.raspberrypi.org/documentation/linux/software/libcamera/README.md) and got a build error:

```
In file included from /home/pi/repos/libcamera-apps/libcamera_jpeg.cpp:10:
/home/pi/repos/libcamera-apps/libcamera_app.hpp: In member function ‘void LibcameraApp<OPTIONS>::StartCamera()’:
/home/pi/repos/libcamera-apps/libcamera_app.hpp:367:37: error: ‘FrameDurations’ is not a member of ‘controls’
   if (!controls_.contains(controls::FrameDurations))
```

This seems to be happening because `FrameDurations` was recently split into `FrameDuration` and `FrameDurationLimits` ([commit here in a github mirror](https://github.com/kbingham/libcamera/commit/19772ffe102ab2e72d0f9f1403e0c02fcca4424d)).

The problem upstream commit was only 3 days ago :-). I might skip over installing the apps at the moment, but thought I'd file the issue.

**Comment by davidplowman** [comment]
Thanks very much for this. It's a minor API change in libcamera. We've merged this now so I'll close the issue!
