### ISSUE TITLE
Libcamera-apps not available for Ubuntu 22.04

### ISSUE THREAD

**Issue by jtillman** [raspberrypi/libcamera-apps#388]
After install Ubuntu 22.04 onto my raspberry pi, you are not able to download libcamera-apps or libcamera-apps-lite.
 
Is someone actively working on making these available using: "sudo apt install libcamera-apps"?

**Comment by naushir** [comment]
You will have to speak with the Ubuntu support teams about this.  We do not maintain their distribution.
