### ISSUE TITLE
[DOC] Add instructions for a full build of libcamera-apps

### ISSUE THREAD

**Issue by pakal** [raspberrypi/libcamera-apps#399]
To fully build libcamera-apps (with libav-related options), I've found that these APT packages were needed : libavcodec-dev, libavutil-dev, libavformat-dev and libavdevice-dev

Woudl it please be possible to add them to https://www.raspberrypi.com/documentation/accessories/camera.html#building-libcamera-apps ?

**Comment by naushir** [comment]
This has already been updated here: https://github.com/raspberrypi/documentation/pull/2673
At some point it will be merged into the main documentation repo.

**Comment by pakal** [comment]
Nice, sorry didn't see that  ^^
