### ISSUE TITLE
Please make releases 

### ISSUE THREAD

**Issue by supertobi** [raspberrypi/libcamera-apps#402]
Please make releases. 
Releases make it easier:
- for the user to follow development.
- for packager to create packages.
- to talk about bugs.
- to compare forks.

**Comment by naushir** [comment]
Thank you for raising this issue!

All our releases happen through our public apt repos.  As such, we do not provide releases through github.  This is purely a place to provide source code and issue tracking.  However, all our apt releases are tagged with the commit sha they were build with.  You can obtain the sha by using the ``--version`` command line agrument:

```
pi@raspberrypi:~ $ libcamera-hello --version
libcamera-apps build: b89cc36c3872 19-10-2022 (13:11:40)
libcamera build: v0.0.1+21-7c855784
```

This ought to be sufficient for manual release tracking.

**Comment by naushir** [comment]
Another thought, would tagging this repo when we make releases make things easer for you?

**Comment by supertobi** [comment]
> Another thought, would tagging this repo when we make releases make things easer for you?

Yes, that would be wonderful. That's all I need.

**Comment by naushir** [comment]
Great, I'll mark this as resolved then!
