### ISSUE TITLE
libcamera-vid tcp stream issue

### ISSUE THREAD

**Issue by StarryDing** [raspberrypi/libcamera-apps#414]
When I use **libcamera-vid -t 0 --inline --listen -o tcp://0.0.0.0:8088** to perform video push stream,it will be shoutdown when the client shoutdown. How to make it still work(perform video push stream) otherwise be shoutdown if the client close? 
![image](https://user-images.githubusercontent.com/53610587/203784341-03f2e889-1108-419f-a009-a017c8309fd7.png)

**Comment by naushir** [comment]
Can you try streaming with libav and see if that helps you?

```
libcamera-vid -t 0 --codec libav --libav-format mpegts -o "tcp://0.0.0.0:8888?listen=1"
```

**Comment by naushir** [comment]
Any update on this issue?

**Comment by naushir** [comment]
If there are no further updates, I will close this down shortly.

**Comment by naushir** [comment]
Resolving now.  Feel free to open a new issue if you are still having problems.
