### ISSUE TITLE
[BUG] std::bad_alloc when using `--metadata` and `--codec yuv420`

### ISSUE THREAD

**Issue by ptoews** [raspberrypi/libcamera-apps#418]
I'm getting the following message followed by program termination when using the mentioned flags:

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

Removing `--metadata` or choosing a different codec prevents this crash. It also seems to depend on framerate, if I set `--framerate 1` it takes longer until it happens, with default settings it happens within the first 1-2 seconds. It's also reproducible every time I try.

Here is the debugging report:
[bug-report.txt](https://github.com/raspberrypi/libcamera-apps/files/10132017/bug-report.txt)

**Comment by naushir** [comment]
Fix is available at https://github.com/raspberrypi/libcamera-apps/pull/420

**Comment by naushir** [comment]
This fix should now be merged.  We are in the process of creating a new release on apt, so this fix should find it's way there very soon!

**Comment by ptoews** [comment]
Awesome, you guys are quick!
