### ISSUE TITLE
Convert raws from IMX519

### ISSUE THREAD

**Issue by Schaggo** [raspberrypi/libcamera-apps#419]
Hi!

I want to capture raws as fast as possible with the imx519. As far as I understand it the fastest way is to capture raw bayer data with libcamera-raw and then process the files in a second step. I tried to use PiDNG and arducams utility script. Both don't seem to work.

Do you have a hint how to produce a DNG from the raws?

Thanks for your time!

**Comment by davidplowman** [comment]
Hi, thanks for the question. libcamera-raw aims to save raw files as fast as it can and therefore outputs the data to a giant flat file with no formatting information at all. You would have to convert this into a set of DNGs yourself afterwards.

However, libcamera-still will capture DNGS for you that you should be able to use directly. Try
```
libcamera-still -r -o test.jpg
```
which should save a test.dng file. But this method will not capture DNGs at anywhere near the same framerate.

**Comment by Schaggo** [comment]
Thanks, David! 

I am just starting with bayer data in general, but my uneducated idea would be to simply store the options used for the capture in a separate file and then load both into `dng_save(mem, info, payload->metadata, filename, app.CameraId(), options);` 

Does that make sense to you?

**Comment by Schaggo** [comment]
Ok, that sounds great! Thanks!
