### ISSUE TITLE
[Feature Request] Extension/plugin interface for custom post-processing stages

### ISSUE THREAD

**Issue by lkijanovic** [raspberrypi/libcamera-apps#422]
I am currently working on a lot of different custom post-processing stages for stream overlays and some CV algorithms.
I was wondering if there are any future plans to implement some sort of plugin interface that would allow users to provide their post-processing stages as, e.g. .so libraries?

There are, I believe, several benefits of something like this:
- Easier development of custom post-processing for end users
- Moving some external requirements from the core to the plugins (e.g. plugins would link to OpenCV and TensorFlow directly)
- This also lays the groundwork to maybe allow post-processing to be written in scripting languages like Python in the future

If there is any interest at all in something like this, I would be more than willing to contribute :blush:

**Comment by naushir** [comment]
@lkijanovic there is a plugin interface that we provide to libcamera-apps.  Examples can be found [here](https://github.com/raspberrypi/libcamera-apps/tree/main/post_processing_stages), and there is further documentation found [here](https://www.raspberrypi.com/documentation/computers/camera_software.html#post-processing) and [here](https://www.raspberrypi.com/documentation/computers/camera_software.html#writing-your-own-post-processing-stages).

If there is any further information needed, feel free to open another issue.
