### ISSUE TITLE
Flicker Period?

### ISSUE THREAD

**Issue by bhjelstrom** [raspberrypi/libcamera-apps#444]
Looking for an example utilizing the RPI IPA AGC's SetFlickerPeriod(). Getting pretty bad banding at low exposures which is a regression from the legacy stack.

**Comment by davidplowman** [comment]
Just out of curiosity, what do you mean by "low exposures"? The legacy stack had no ability to suppress flicker when the exposure time was less than 10ms. Would you be able to report the exposure time and gain you're seeing in both the "good" and "bad" cases? Thanks!

In the meantime I'll look into this problem. The principal issue, I believe, is that libcamera has no controls that plumb into the `SetFlickerPeriod()` method.

**Comment by naushir** [comment]
This has now been merged into libcamera.  The accompanying change for libcamera-apps to enable flicker control is at https://github.com/raspberrypi/libcamera-apps/pull/544.

**Comment by naushir** [comment]
Flicker control is now available with the ``--flicker-period`` command line option.  Note that you need the very latest libcamera + libcamera-apps top-of-tree builds for this to be available.
