### ISSUE TITLE
Error: failed to import fd 18 Aborted

### ISSUE THREAD

**Issue by BrendanHenryGithub** [raspberrypi/libcamera-apps#46]
Env: 
- 4B (with 4G memory), 64bit Pi OS
- uanme -a:   
![image](https://user-images.githubusercontent.com/31235882/124383445-0bf04900-dcff-11eb-8a7a-62eb4794f781.png)
- /boot/config.txt:
![image](https://user-images.githubusercontent.com/31235882/124383463-2aeedb00-dcff-11eb-8ead-b3f9484308dd.png)

Problem:
![image](https://user-images.githubusercontent.com/31235882/124383492-5376d500-dcff-11eb-929d-e1ff61834897.png)

Remarks:
- I try rerun cmake with this in this project build dir:  cmake -DENABLE_COMPILE_FLAGS_FOR_TARGET=none ..      (but have the same problem.)

**Comment by davidplowman** [comment]
Hi, thanks for this report. Indeed I've seen this error reported before (on a 1GB Pi 4 running a 32-bit OS) but the thread rather dried up. But I'd like to get to the bottom of this.

Firstly, I've been running a 64-bit build with exactly the same data (via `uname -a`) as yours, and I've copied your /boot/config.txt verbatim, and (you've guessed it) it works fine. So:

1. First let's double-check the firmware version (type `vcgencmd version`). I have:
May 27 2021 14:03:06 
Copyright (c) 2012 Broadcom
version 7d9a298cda813f747b51fe17e1e417e7bf5ca94d (clean) (release) (start_x)
2. Have you installed anything extra in your build, and are you running this straight after booting up with nothing else going on?
3. Are you running headless, or logged in via ssh, or anything like that? I'm assuming you're logged directly in the Pi with a local screen attached. (BTW, what resolution is the screen? I think `tvservice -s` would tell you)
4. The failure is clearly [here](https://github.com/raspberrypi/libcamera-apps/blob/main/egl_preview.cpp#L318). Would you be able to fish out the actual EGL error? So you'd have to add something like `+ " " + std::to_string(eglGetError())` to the end of that error runtime error message, and re-run make.
5. In the meantime I'll consult with some folks who know rather about all this, perhaps there's some more debug we can enable or look at. (I don't suppose `dmesg` reports anything that looks related?)

Thanks!

**Comment by BrendanHenryGithub** [comment]
Thanks for your help!
1.  My vcgencmd version is the same as yours.
2.  First time it prompt: can not find libGLESv2.so,  and i google and run : apt install libgles2-mesa-dev libglfw3-dev.
3.  I  logged in via ssh (Mobaxterm tool with X server).  tverservice output:
![image](https://user-images.githubusercontent.com/31235882/124387460-62668300-dd11-11eb-93ec-0b8f5394b23d.png)
4.  I try like this in egl_preview.cpp:
![image](https://user-images.githubusercontent.com/31235882/124387483-76aa8000-dd11-11eb-801e-6fd41bd090c0.png)
rerun output:
![image](https://user-images.githubusercontent.com/31235882/124387532-9d68b680-dd11-11eb-96e0-81775f0d4771.png)
I google for this error code. Look like this:
![image](https://user-images.githubusercontent.com/31235882/124387596-d1dc7280-dd11-11eb-9a65-0ba6c588691d.png)

**Comment by BrendanHenryGithub** [comment]
Some info maybe useful:
![image](https://user-images.githubusercontent.com/31235882/124389053-11a65880-dd18-11eb-8b1b-7538a88bdc86.png)

![image](https://user-images.githubusercontent.com/31235882/124389816-71eac980-dd1b-11eb-818e-79a0a267b7e3.png)

**Comment by davidplowman** [comment]
Hi again

Firstly, It sounds to me like there might be something wrong about your installation. The fact that you've had missing libraries and installed some others is clearly not right - the correct procedure is [here](https://github.com/raspberrypi/libcamera-apps#readme)

Having said that, I assume from your comments that you're running headless. Are you by any chance trying to use X forwarding? Our EGL-based preview shares dmabufs from the camera with the GPU on the Pi and I have no idea whether that's even possible with X forwarding. It's certainly not supported at the moment, but I'll have to take advice on that. In the meantime, you might find that qcam with its Qt copying-based preview would work.

**Comment by BrendanHenryGithub** [comment]
Thanks a lot. 
Yes,  according to your suggestion, i found the core of problem is about X forwarding. When i turn off X Server and  hook up the monitor everything is ok.

**Comment by davidplowman** [comment]
We've pushed a change which provides another implementation of the preview window that doesn't use zero-copy buffer sharing or GPU acceleration. It's implemented using Qt and can be enabled using (for example) `libcamera-hello --qt-preview`. Note that it's very slow compared with the other preview implementations (so we never use it unless it's requested explicitly), and it would be best to avoid large images. But it does work with X forwarding. I think that's enough to close this thread - but please file a new issue if anything crops up.

**Comment by Petros626** [comment]
@BrendanHenryGithub 

Hey there,

I got the same problem like you but in my case it was `what(): failed to import fd19`. So with the installation from here (https://github.com/raspberrypi/libcamera-apps#readme) it should work ?

Would appreciate it, if you could answer this.

**Comment by Petros626** [comment]
@BrendanHenryGithub 

Hey there,

I got the same problem like you but in my case it was `what(): failed to import fd19`. So with the installation from here (https://github.com/raspberrypi/libcamera-apps#readme) it should work ?

Would appreciate it, if you could answer this.
