### ISSUE TITLE
OV9281 External Trigger Support

### ISSUE THREAD

**Issue by fxweidinger** [raspberrypi/libcamera-apps#469]
Hi! 

hope this is the right place to ask this: 
In one of our Projects, we use the Arducam OV9281. We want to transition to libcamera, since they have deprecated their MIPI Driver and it seems like a much cleaner solution and we also want to switch Bullseye.

Now for the actual problem: Our product relies on the external trigger functionality. After skimming through this repo and a bit of trial-and-error, I'm not really sure this is supported in libcamera with this module.
I've seen that #5260 e6a7eed8db3c41fce11d8bf7005819f1f302a9ee added support for the OV7251 external trigger, so maybe the process would be similar? 
I'd really appreciate it if some could tell me, if I can somehow get this work.

**Comment by 6by9** [comment]
I thought I'd already added it, but don't see such a patch.

OV9281 was a downstream patch. Full support has now been merged into the mainline ov9282 driver, so currently from 6.2 we will be using that. I suspect I'll backport it to 6.1 as well. Changes aren't going to be made to the ov9281 driver on 5.15 now.

The process will be near identical to ov7251, but the registers involved may be different. I'll see what I can dig out.

Seeing as this repo is a request for a Linux kernel driver change, https://github.com/raspberrypi/linux is the appropriate repo. I'll see if I can find someone with appropriate permissions to move this issue.

**Comment by fxweidinger** [comment]
Ah, I'm sorry, I had both repos open and got confused when opening the issue... I was wondering why the Commit Hash wouldn't link automatically, that explains it.
Sounds like good news though, thanks!
