### ISSUE TITLE
Screen flickering when using IR-cut

### ISSUE THREAD

**Issue by RagdollCar** [raspberrypi/libcamera-apps#474]
https://user-images.githubusercontent.com/88408024/220297763-68e5ce9f-82a8-485c-86ea-47af7c3a3c9d.mp4

IMX477 running on RPI4. This camera has an IR-cut which is enabled each time the light conditions get worse. During driving IR-cut gets enabled/disabled frequently which causes screen flickering.

I have already reported this to arducam support with few questions, but I also want to ask if it is possible to fix in the source code?

Of course the simple solution is to plug-off the IR-cut cables and not use it - then everything work fine.

**Comment by 6by9** [comment]
Raspberry Pi don't sell an IMX477 with controllable IR cut filter, so largely you need to go back to your vendor.

That corruption looks like interference on the CSI-2 interface - nothing in software can solve that.

**Comment by RagdollCar** [comment]
This is Arducam IMX477 plugged to RPI4. Ok, I will talk to the vendor.
