### ISSUE TITLE
[BUG] libcamera-raw --frames not working ?

### ISSUE THREAD

**Issue by Gordon999** [raspberrypi/libcamera-apps#479]
Using libcamera-raw -n --segment 1 -o /home/pi/Pictures/test_%04d.raw -t 0 --frames 5 the --frames is ignored.

**Comment by naushir** [comment]
``--frames`` is only available with libcamera-vid unfortunately.  I'll look to adding it to libcamera-raw, but this will be a low priority task.

**Comment by Gordon999** [comment]
Thanks
