### ISSUE TITLE
No frame data was collected.

### ISSUE THREAD

**Issue by wangjunjie1996** [raspberrypi/libcamera-apps#495]
**Describe the bug**
When using "libcamera-still -r -o test.jpg --width 4000 --height 2000 --gain 1 -awbgain 1,1 --shutter 3000000 --immediate", the data is available for the first time, and the picture is normal for 1.7M, but there is no data behind it, and the picture is only 127kb in black.

**Bug report**
[bug.txt](https://github.com/raspberrypi/libcamera-apps/files/11076132/bug.txt)

**Additional context**
I view the information by adding my own log and compiling and installing locally. The following screenshot shows the information.  
![图片](https://user-images.githubusercontent.com/51921698/227878894-521f949f-bab5-4d95-a21b-d2d631a94d74.png)  
![图片](https://user-images.githubusercontent.com/51921698/227879608-9150481f-6a23-461f-a0bd-770d8ccd053e.png)  

Normal should be as follows  

![图片](https://user-images.githubusercontent.com/51921698/227879858-293b986c-21fc-4cc9-9302-25c528da2f47.png)

And the buf.sequence in "V4L2VideoDevice::dequeueBuffer" is 0,  and it is normal only if it is not 0.

**Comment by naushir** [comment]
Would you be able to attach the file created when you run the ``camera-bug-report`` tool to this issue please?

**Comment by naushir** [comment]
Given you are using an Arducam camera (and associated closed source libraries), we cannot provide support for this.  Please seek out help in the Arducam forums.
