### ISSUE TITLE
make x11 optional and/or wayland support

### ISSUE THREAD

**Issue by pseiderer** [raspberrypi/libcamera-apps#5]
Feature request for x11 as configure option and/or (optional) wayland support (see [1])...

[1] http://lists.busybox.net/pipermail/buildroot/2021-January/302594.html

**Comment by davidplowman** [comment]
I'll put this "on the list", but I'm afraid it's unlikely very much will happen until Wayland is more mainstream on the Raspberry Pi (which is the only development platform we have). Sorry...

**Comment by davidplowman** [comment]
I think I'm probably going to close this one for now. We'll come back to it once Wayland is more mainstream on the Pi.
