### ISSUE TITLE
Feature request: Transpose (e.g. 90degrees rotation)

### ISSUE THREAD

**Issue by 2konrad** [raspberrypi/libcamera-apps#505]
Is there a plan to enable the **Transpose** Transform?
E.g. I cannot rotate an image by 90degrees with libcamera.

https://github.com/raspberrypi/libcamera-apps/blob/5a835b89849f38808353eabdd46ee4fcb75fdfad/core/options.cpp#L240

**Comment by naushir** [comment]
Unfortunately because of hardware limitations, we cannot add support for transpose operations in the libcamera pipeline.  This will have to be done as a separate post-processing operation.
