### ISSUE TITLE
Module 3 modes

### ISSUE THREAD

**Issue by GuyPerets106** [raspberrypi/libcamera-apps#515]
Hi, I'm using CM4 + Camera Module 3 in my project.
When using `libcamera-vid --list-cameras` I get this output:
![צילום מסך 2023-06-12 ב-12 07 35](https://github.com/raspberrypi/libcamera-apps/assets/79912473/4342a88b-7fd8-4408-b39f-0303eba78149)
and I'm not sure I understand what the elements mean - in mode 1536x864 for example , what `(768,432)/3072x1728 crop` means? In the other modes, it says `(0,0)/4608x2592 crop` so what's special about this first mode? 

In another review of the product (https://www.cnx-software.com/2023/01/23/raspberry-pi-camera-module-3-review-hdr-autofocus-wide-angle-and-noir-camera/) I saw he got different results while using the same command and the same camera:
![צילום מסך 2023-06-12 ב-12 25 20](https://github.com/raspberrypi/libcamera-apps/assets/79912473/6b621c88-b1d3-4d4e-9181-66908fd5104d)

In another issue I mentioned the problem of narrower FOV when using the 1536x864 mode , so if the text I don't understand is related to the FOV crop , how the review specify otherwise? maybe it can fix my problem.. 

Another question is more general - Is there any expectation for when does the multiple camera recording support should arrive on libcamera-vid? I saw this in https://libcamera.org/faq.html:
_Can libcamera handle multiple cameras simultaneously?
libcamera can support multiple cameras within a system, but allows only a single application to consume the streams from a camera. An application must ‘acquire’ a Camera to start operations on it, and should release it when finished. Logical cameras where multiple cameras are treated as a single camera is a pipeline and hardware specific extension that will be supported in the future._

Thank you

**Comment by naushir** [comment]
> Hi, I'm using CM4 + Camera Module 3 in my project. When using `libcamera-vid --list-cameras` I get this output: ![צילום מסך 2023-06-12 ב-12 07 35](https://user-images.githubusercontent.com/79912473/245089878-4342a88b-7fd8-4408-b39f-0303eba78149.png) and I'm not sure I understand what the elements mean - in mode 1536x864 for example , what `(768,432)/3072x1728 crop` means? In the other modes, it says `(0,0)/4608x2592 crop` so what's special about this first mode?

The 1536x864 mode is setup for high framerate (120fps) operation.  Because of limitations on the internal pixel clock rate of the sensor, it can only achieve this framerate by sampling a smaller crop of the total active pixel area in the sensor. The mode information above is saying that the crop begins at ``(x, y) == (768, 432)`` from the top left of the sensor, giving you a narrower field of view.  All other modes sample and bin the all active pixels on the sensor, and this will give you the largest possible field of view.

> In another review of the product (https://www.cnx-software.com/2023/01/23/raspberry-pi-camera-module-3-review-hdr-autofocus-wide-angle-and-noir-camera/) I saw he got different results while using the same command and the same camera: ![צילום מסך 2023-06-12 ב-12 25 20](https://user-images.githubusercontent.com/79912473/245101542-6b621c88-b1d3-4d4e-9181-66908fd5104d.png)
> 
> In another issue I mentioned the problem of narrower FOV when using the 1536x864 mode , so if the text I don't understand is related to the FOV crop , how the review specify otherwise? maybe it can fix my problem..

The difference in crop/FoV in the review above is probably down to a bug in the early driver that did not advertise the crop numbers correctly.  If you were to compare the images between that driver and the current up-to-date driver, you will find they would be identical.

> 
> Another question is more general - Is there any expectation for when does the multiple camera recording support should arrive on libcamera-vid? I saw this in https://libcamera.org/faq.html: _Can libcamera handle multiple cameras simultaneously? libcamera can support multiple cameras within a system, but allows only a single application to consume the streams from a camera. An application must ‘acquire’ a Camera to start operations on it, and should release it when finished. Logical cameras where multiple cameras are treated as a single camera is a pipeline and hardware specific extension that will be supported in the future._

Multi-cameras do work correctly today.  If you have 2 devices connected to the CM4, they ought to be listed as 2 separate cameras when you use ``--list-cameras``.  You can then run them concurrently in 2 separate libcamera instances.

**Comment by GuyPerets106** [comment]
Thank you for all the information! 

> Multi-cameras do work correctly today. If you have 2 devices connected to the CM4, they ought to be listed as 2 separate cameras when you use `--list-cameras`. You can then run them concurrently in 2 separate libcamera instances.

I'm currently using the ability to start two different threads, such that every thread recording from a different camera, but the problem I'm facing is that the recording doesn't start at the exact same time, and the frames are not captured in the same time - causing the fast objects I'm trying to track their position are in different heights in the related frames from each camera. There is a way to synchronize the operation of frame capture using this method? So that the camera sensors will capture the frame at the exact same time or with a much smaller delay?

In my original question, I wanted to know if this synchronized capture was the expected multiple-cameras support the FAQ mentioned.

**Comment by naushir** [comment]
> I'm currently using the ability to start two different threads, such that every thread recording from a different camera, but the problem I'm facing is that the recording doesn't start at the exact same time, and the frames are not captured in the same time - causing the fast objects I'm trying to track their position are in different heights in the related frames from each camera. There is a way to synchronize the operation of frame capture using this method? So that the camera sensors will capture the frame at the exact same time or with a much smaller delay?

Unfortunately at this time, there is no way to synchronise the camera startup and framing between multiple cameras though software.

There are provisions for hardware based synchronisation, but only on the IMX477 (HQ Camera) and IMX296 (GS Camera).  Here you can attach a HW strobe line between sensors, but there is still more work to do to get this fully functional. 

> In my original question, I wanted to know if this synchronized capture was the expected multiple-cameras support the FAQ mentioned.

**Comment by naushir** [comment]
If this is now resolved, I'll close this issue shortly.
