### ISSUE TITLE
Unable to set control 0x00980911: Input-/Outputerror

### ISSUE THREAD

**Issue by medem23** [raspberrypi/libcamera-apps#550]
Hi Guys, basically I'm using lib camera to take recordings of 30 minutes (fps=30, size=(1640, 1232)) each and the problem is that I get sometimes this error
[0:13:50.33631661] [2210] ERROR V4L2 v4l2_device.cpp:359 'imx219 10-0010': Unable to set control 0x00980911: Input-/Outputerror

**Comment by naushir** [comment]
This seems to be an I2C error when communicating with the sensor.  Do you by any chance have a touchscreen installed on the Pi?  If so, a recent fix for excessive I2C accesses has been merged (https://github.com/raspberrypi/linux/pull/5545) which may solve your problem.

**Comment by medem23** [comment]
Yes I do have a touchscreen installed.

**Comment by naushir** [comment]
Did you manage to try the kernel fix and see if it fixes your problem?

**Comment by naushir** [comment]
If there are no further updates, I'll close this one down for now.

**Comment by medem23** [comment]
I updated the kernels today and it seems to work (will need to run longer test)., Thank you very much for the help.

**Comment by naushir** [comment]
Great, thanks for confirming!
