### ISSUE TITLE
Using libcamera - Videos(h264) have different lengths although recording time is always 29:50

### ISSUE THREAD

**Issue by medem23** [raspberrypi/libcamera-apps#553]
Hi Guys, basically I'm using lib camera to take recordings of 30 minutes (fps=30, size=(1640, 1232)): 
`
 bitrate 10 Mbps
 encoder = H264Encoder(5000000). # 5 Mbps

 Resolution definition
 lores_size = (640, 480)
 main_size = (1640, 1232)

 Config file for picamera
 config = picam2.create_video_configuration(
        main={"size": main_size},                             
        lores={"size": lores_size},                           
        controls={"FrameDurationLimits": (33333, 33333)},    
        display="lores",                                     
        encode="main",                                        
        buffer_count=8                                        
    )

 Configure the camera
  picam2.configure(config)
`

I'm using PyQt5 timer to switch files every 30 minutes:

`
rec_timer = QtCore.QTimer()

recording_minutes = 30

rec_timer.setInterval(recording_minutes * 60 * 1000)        
           
rec_timer.timeout.connect(switch_filename)
`

Now, my problem is that the video ends up being 29:48 or 29:27 or 29:18 or 29:xx and even sometime 28:xx but they should be 29:50 (I add 10 seconds sleep) but there is no indication of error etc. Are some frames dropped sometimes without warning? I tried increasing the buffer to 12 but that did not help.

**Comment by naushir** [comment]
I think this probably wants to move to the [picamera2](https://github.com/raspberrypi/picamera2) issue tracker.

**Comment by medem23** [comment]
Yes will do, Thanks!
