### ISSUE TITLE
Removing media device /dev/media3 while still in use

### ISSUE THREAD

**Issue by kauai68** [raspberrypi/libcamera-apps#554]
I'm using the following pipeline in OpenCV (4.5.1) VideoCapture running on a RPi (CM4) with OS bullseye 64 bit: 

libcamerasrc camera-name=\"/base/soc/i2c0mux/i2c@1/imx219@10\" " ! appsink name=appsink

The pipeline works and the video is displayed well. However, when I call VideoCapture::release my application crashes with an unhandled exception. The error is: DeviceEnumerator device_enumerator.cpp:166 Removing media device /dev/media3 while still in use.

Stack trace:
libcamera-base.so.0.0!libcamera:Thread:postMessage
...
libcamera.so.0.0!libcamera::FrameBufferAllocator::~FrameBufferAllocator()
...
libgstreamer-1.0.so.0!g_object_unref
...
libopencv_videoio.so.4.5!cv::VideoCapture::release()

**Comment by naushir** [comment]
This doesn't sound like it's specifically to do with libcamera-apps or the Raspberry Pi pipeline handler.  I think this question might need to be asked on the [libcamera mailing list](https://lists.libcamera.org/listinfo/libcamera-devel).
