### ISSUE TITLE
update camera parameter during live preview

### ISSUE THREAD

**Issue by akshar2324** [raspberrypi/libcamera-apps#558]
i want to update exposure and gain during camera live preview and right now i am using libcamera still command with parameter attached is it possible to change parameter during live preview?

**Comment by naushir** [comment]
This is not possible with libcamera-apps, parameters are set on startup and never change.  However, this is easily done with [picamera2](https://github.com/raspberrypi/picamera2) as that runs the camera in an interactive environment.
