### ISSUE TITLE
[BUG] libcamera-still.cpp errors from v1.2.1

### ISSUE THREAD

**Issue by ManjunathaVG-MathWorks** [raspberrypi/libcamera-apps#589]
Hi, 

From the following link, I got to know that I need to use  v1.2.1 for compiling apps manually,
https://github.com/raspberrypi/libcamera-apps/issues/575

But when I tried to compile libcamera-still, I encountered the following error. Here are the steps I followed:

$ sudo apt-get update
$ sudo apt-get install libcamera-apps licamera-dev libcamera0 libboost-dev -y
$ # Download libcamera-still.cpp file from v1.2.1 repo and save it as still.cpp
$ g++ -std=c++17 -o still still.cpp -lcamera -lcamera_app  -I/usr/include/libcamera -I/usr/include/libcamera-apps
pi@raspberrypi:~ $ g++ -std=c++17 -o still still.cpp -lcamera -lcamera_app  -I/usr/include/libcamera -I/usr/include/libcamera-apps
/usr/bin/ld: /tmp/ccm0e3gd.o: undefined reference to symbol '_ZN5boost15program_options8validateERNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS9_EEPbi'
/usr/bin/ld: /lib/arm-linux-gnueabihf/libboost_program_options.so.1.74.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
pi@raspberrypi:~ $

Is there anything that I am missing?

P.S: I am using the same hardware setup as mentioned in issue-575

Thanks,
Manjunatha

**Comment by naushir** [comment]
You need to add ``-lboost_program_options`` to your command options.

I would wholly recommend using a build system like meson or cmake if you are going to build relatively complex applications with external libraries and dependencies.  It cuts out all the guessing of what to include in the command line like this.
