### ISSUE TITLE
[BUG]"--tuning-file" parameter is invalidated

### ISSUE THREAD

**Issue by tom-ard** [raspberrypi/libcamera-apps#592]
"LIBCAMERA_RPI_TUNING_FILE" reads in the libcamera library is a vacant value.
As can be seen from the log, libcamera read "LIBCAMERA_RPI_TUNING_FILE" Before the apps settings.
![image](https://github.com/raspberrypi/libcamera-apps/assets/100827463/3f591339-42b5-43b1-9fc9-cb22f6f8485f)

Print information in the libcamera library
![image](https://github.com/raspberrypi/libcamera-apps/assets/100827463/9b36cfe8-5030-4235-a444-38b7654f324c)

Print infomation in the libcamera-apps
![image](https://github.com/raspberrypi/libcamera-apps/assets/100827463/f2b31c48-7c4d-43af-a568-dbcece8ae3df)

**Comment by naushir** [comment]
Thank you for the report.  You are right, a recent change has broken this functionality.  I will send a proposed fix shortly to get this working again.

**Comment by naushir** [comment]
This should hopefully be fixed with https://github.com/raspberrypi/libcamera-apps/pull/593.  Would you be able to give this a try and report back?

**Comment by tom-ard** [comment]
Okay, I'll start testing now

**Comment by tom-ard** [comment]
The problem was solved perfectly, thank you.
![image](https://github.com/raspberrypi/libcamera-apps/assets/100827463/800f5e44-f175-4659-a989-d0fbdba3ee85)

**Comment by naushir** [comment]
Thanks for confirming, the change has now been merged.
